version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot-detector/bd-mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_bot_buster
      - MYSQL_USER=botssuck
      - MYSQL_PASSWORD=botdetector
    volumes:
      - './mount:/var/lib/mysql'
    ports:
      - "3306:3306"
    networks:
      - botdetector-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot_bot_buster"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 5s

networks:
  botdetector-network: